"""Add performance indexes to Member and Payment models

Revision ID: 01ccdfbe3757
Revises: bca890da18a1
Create Date: 2025-12-03 14:54:40.254617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ccdfbe3757'
down_revision = 'bca890da18a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('member_referral_code_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_member_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_referral_code'), ['referral_code'], unique=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index('idx_payment_year_month_status', ['year', 'month', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_year'))
        batch_op.drop_index(batch_op.f('ix_payment_status'))
        batch_op.drop_index(batch_op.f('ix_payment_month'))
        batch_op.drop_index(batch_op.f('ix_payment_member_id'))
        batch_op.drop_index('idx_payment_year_month_status')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_referral_code'))
        batch_op.drop_index(batch_op.f('ix_member_phone'))
        batch_op.drop_index(batch_op.f('ix_member_name'))
        batch_op.create_unique_constraint(batch_op.f('member_referral_code_key'), ['referral_code'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
